name: "BUG"
description: "File a bug report"
title: "[Bug] <title>"
labels: [Bug]
body:
  - type: input
    id: User
    attributes:
      label: Roblox User
      description: Please provide your Roblox username.
      placeholder: ex. roblox
    validations:
      required: true
  - type: textarea
    id: Details
    attributes:
      label: Describe the bug.
      description: Please describe the bug and provide steps to reproduce it.
    validations:
      required: false
  - type: textarea
    id: Media
    attributes:
      label: Attach images or videos of the bug.
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: Before Submitting
      description: Please check the boxes below before submitting.
      options:
        - label: The details of this report are indeed true.
          required: true
